### ISSUE TITLE
Improve navigation in polls app.

### ISSUE THREAD

**Issue by sirateek** [sirateek/ku-polls#10]
## Task
- [x] On the index page, Add links to the details and results page for each of the questions.
- [x] Only show the vote links for the question that accepting the new vote.
- [x] Add the "Back to List of Polls" link on the detail page.
