### ISSUE TITLE
Prepare the Question Model to stop accepting vote after the `end_date`

### ISSUE THREAD

**Issue by sirateek** [sirateek/ku-polls#8]
## Task
- [x] Add `end_date` attribute in Question Model as a DateTimeField.
- [x] Add `is_published()` method that returns True if the current date is on or after question’s publication date
- [x] Add `can_vote()` method that returns True if voting is currently allowed for this question
- [x] Add unit test for `is_published()` and `can_vote()`
